//LLAMADA DE LIBRERIAS INTERNAS
#include <iostream>
//LLAMADA DE LIBRERIAS EXTERNAS
#include "L1EstructuraGrupo5.h"
//ESPACIO DE TRABAJO DE ENTRADA Y SALIDA DE DATOS
using namespace std;
/*
DECALRACION DE FUNCIONES U PROCEDIMIENTOS Y INICIALIZACION DE ELLAS
FUNCION PRINCIPAL MAIN()
*/
int main(){
    //LLAMADA DE FUNCIONES
    PortadaGrupo5();
    MenuGrupo5();
    //RETORNOS DE LA FUNCION MAIN()
    return 0;
}
